### ISSUE TITLE
Port to ROS2

### ISSUE THREAD

**Issue by cmosig** [dcmlr/kitti360_ros_player#3]
Create a branch `ros2` and adjust launch file and code such that everything works with ROS2.

**Comment by cmosig** [comment]
see ros2 branch

**Comment by amjad-haider** [comment]
is this issue still active? Can i work on this issue?

**Comment by cmosig** [comment]
There is actually a ROS2 branch that is mostly done I think. Feel to improve that one! Please read the note at The beginning of the readme.
