### ISSUE TITLE
pip install requirement.txt  。 i run this in a pure conda enviroment ,is not ok ~ which version could be satisfied? can u help me 

### ISSUE THREAD

**Issue by HanXiao68** [dcmlr/kitti360_ros_player#7]
as the title u can see

**Comment by cmosig** [comment]
I don't think you can use `pip` in a conda environment. You may want to check which python packages you have installed in your conda environment and compare that with the packages listed in `requirement.txt`. [This](https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment) may help.

**Comment by HanXiao68** [comment]
thanks for your reply ~ 
but i tried the command "unset PYTHONPATH" in that link 。Also come wrong as : ERROR: Could not find a version that satisfies the requirement rospy>=1.15.14 (from versions: none)
ERROR: No matching distribution found for rospy>=1.15.14
maybe,because of my conda enviroment python is 3.10.X 。not support more perfect the ROS than python2.7

**Comment by cmosig** [comment]
You will need to look in the answers section of the stackoverflow link I sent, not the question.

Anyway, maybe install the packages one by one (from requirement.txt) using conda (because you have a conda environment, not pip). For example: `conda install -c conda-forge ros-rospy`.

**Comment by cmosig** [comment]
I am going to close this issue, because it is unrelated to the repo.
